In [17]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_validate
from sklearn.metrics import classification_report, confusion_matrix

from utils import read_csv_custom
from config import X_TRAIN_PATH, Y_TRAIN_PATH, X_VAL_PATH, Y_VAL_PATH, TSFM_TRAIN_DIR, TSFM_VAL_DIR

In [18]:
X_train = read_csv_custom(X_TRAIN_PATH)
y_train = np.loadtxt(Y_TRAIN_PATH, delimiter=',')

X_val = read_csv_custom(X_VAL_PATH)
y_val = np.loadtxt(Y_VAL_PATH, delimiter=',')

In [13]:
clf = RandomForestClassifier(n_estimators=1000, random_state=0)
clf.fit(X_train, y_train)
y_train_pred = clf.predict(X_train)

In [14]:
print(classification_report(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       179
         1.0       1.00      1.00      1.00        22
         2.0       1.00      1.00      1.00       263

    accuracy                           1.00       464
   macro avg       1.00      1.00      1.00       464
weighted avg       1.00      1.00      1.00       464

[[179   0   0]
 [  0  22   0]
 [  0   0 263]]


In [15]:
y_val_pred = clf.predict(X_val)
print(classification_report(y_val, y_val_pred))
print(confusion_matrix(y_val, y_val_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.03      0.06        61
         1.0       0.00      0.00      0.00        50
         2.0       0.00      0.00      0.00         0

    accuracy                           0.02       111
   macro avg       0.33      0.01      0.02       111
weighted avg       0.55      0.02      0.03       111

[[ 2  0 59]
 [ 0  0 50]
 [ 0  0  0]]


/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
clf = RandomForestClassifier(n_estimators=1000, random_state=0)
scores = cross_validate(clf, X_train, y_train, cv=None, scoring='f1')
print(scores['test_score'])

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

# Random Forest on Linear PCA

In [6]:
X_train = read_csv_custom(TSFM_TRAIN_DIR / 'linear_pca.csv')
y_train = np.loadtxt(Y_TRAIN_PATH, delimiter=',')

X_val = read_csv_custom(TSFM_VAL_DIR / 'linear_pca.csv')
y_val = np.loadtxt(Y_VAL_PATH, delimiter=',')

In [7]:
clf = RandomForestClassifier(n_estimators=1000, random_state=0)
clf.fit(X_train, y_train)
y_train_pred = clf.predict(X_train)

In [8]:
print(classification_report(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       179
         1.0       1.00      1.00      1.00        22
         2.0       1.00      1.00      1.00       263

    accuracy                           1.00       464
   macro avg       1.00      1.00      1.00       464
weighted avg       1.00      1.00      1.00       464

[[179   0   0]
 [  0  22   0]
 [  0   0 263]]


In [9]:
y_val_pred = clf.predict(X_val)
print(classification_report(y_val, y_val_pred))
print(confusion_matrix(y_val, y_val_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.03      0.06        61
         1.0       0.00      0.00      0.00        50
         2.0       0.00      0.00      0.00         0

    accuracy                           0.02       111
   macro avg       0.33      0.01      0.02       111
weighted avg       0.55      0.02      0.03       111

[[ 2  0 59]
 [ 0  0 50]
 [ 0  0  0]]


/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
